### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'update'

### ISSUE THREAD

**Issue by seamusabshere** [faradayio/cage#3]
```
seamus@pirlo:~/code/conductor_test$ conductor new myapp
Generating: .gitignore
Generating: pods/common.env
Generating: pods/db.yml
Generating: pods/frontend.yml
Generating: pods/migrate.yml
Generating: common.env
Generating: common.env
Generating: common.env

seamus@pirlo:~/code/conductor_test$ cd myapp/

seamus@pirlo:~/code/conductor_test/myapp$ tree .
.
└── pods
    ├── common.env
    ├── db.yml
    ├── frontend.yml
    ├── migrate.yml
    └── overrides
        ├── development
        │   └── common.env
        ├── production
        │   └── common.env
        └── test
            └── common.env

5 directories, 7 files

seamus@pirlo:~/code/conductor_test/myapp$ conductor repo list
rails_hello               https://github.com/faradayio/rails_hello.git

seamus@pirlo:~/code/conductor_test/myapp$ conductor up
Creating network "myapp_default" with the default driver
Pulling db (postgres:latest)...
latest: Pulling from library/postgres
8ad8b3f87b37: Pull complete
c5f4a4b21ab6: Pull complete
ba05db8b0a52: Pull complete
47b491cd21ab: Pull complete
d70407e3e64d: Pull complete
295c246dd69f: Pull complete
89bc4bb8bcfd: Pull complete
106ff44c5f06: Pull complete
867cd91e76bb: Pull complete
a227948d6d8c: Pull complete
fc2ec20bdaf0: Pull complete
Digest: sha256:1115f095242a490cb79561124a79125e25b0595d5ae47d44fab5b4c1cd10735f
Status: Downloaded newer image for postgres:latest
Creating myapp_db_1
WARNING: Found orphan containers (myapp_db_1) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
Building web
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "compose/cli/main.py", line 61, in main
  File "compose/cli/main.py", line 113, in perform_command
  File "compose/cli/main.py", line 835, in up
  File "compose/project.py", line 382, in up
  File "compose/service.py", line 305, in ensure_image_exists
  File "compose/service.py", line 727, in build
  File "site-packages/docker/api/build.py", line 104, in build
  File "site-packages/docker/utils/decorators.py", line 46, in inner
AttributeError: 'NoneType' object has no attribute 'update'
docker-compose returned -1
Error: Error running docker-compose

seamus@pirlo:~/code/conductor_test/myapp$ conductor up
myapp_db_1 is up-to-date
WARNING: Found orphan containers (myapp_db_1) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
Building web
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "compose/cli/main.py", line 61, in main
  File "compose/cli/main.py", line 113, in perform_command
  File "compose/cli/main.py", line 835, in up
  File "compose/project.py", line 382, in up
  File "compose/service.py", line 305, in ensure_image_exists
  File "compose/service.py", line 727, in build
  File "site-packages/docker/api/build.py", line 104, in build
  File "site-packages/docker/utils/decorators.py", line 46, in inner
AttributeError: 'NoneType' object has no attribute 'update'
docker-compose returned -1
Error: Error running docker-compose
```

**Comment by emk** [comment]
```sh
docker --version
docker-compose --version
```

**Comment by seamusabshere** [comment]
```
$ docker --version
Docker version 1.12.0, build 8eab29e, experimental

$ docker-compose --version
docker-compose version 1.8.0, build f3628c7
```

**Comment by emk** [comment]
Could [this be related](https://github.com/docker/compose/issues/3780)?

**Comment by emk** [comment]
This is caused https://github.com/docker/compose/issues/3780, which is triggered by a `.docker/config.json` containing:

```json
HttpHeaders": {
  "User-Agent": "Docker-Client/1.12.0 (darwin)"
}
```

Remove that bit and you'll be fine. This has been fixed upstream, but I'll leave this open until a new version of `docker-compose` has been released.
